// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;










/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFW07URBmrwnmIHacq57WIO3knlw81f4c',
    appId: '1:666491525925:web:b3d65e71c44b333d63d8cc',
    messagingSenderId: '666491525925',
    projectId: 'fir-cloud-f6c2a',
    authDomain: 'fir-cloud-f6c2a.firebaseapp.com',
    storageBucket: 'fir-cloud-f6c2a.appspot.com',
    measurementId: 'G-KD6ZCNLE4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnlWMNPRsxBcKZg2cRzsQFf5vZA5jtUC8',
    appId: '1:666491525925:android:2f3820e384559f0b63d8cc',
    messagingSenderId: '666491525925',
    projectId: 'fir-cloud-f6c2a',
    storageBucket: 'fir-cloud-f6c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjDiiqXjMFSNWI10-tP9nh-EFLDue0a8',
    appId: '1:666491525925:ios:ff348f8b4a0b0d2463d8cc',
    messagingSenderId: '666491525925',
    projectId: 'fir-cloud-f6c2a',
    storageBucket: 'fir-cloud-f6c2a.appspot.com',
    iosClientId: '666491525925-5jfon156rue0crp1l8ie7e5se6a0sahh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTjDiiqXjMFSNWI10-tP9nh-EFLDue0a8',
    appId: '1:666491525925:ios:ff348f8b4a0b0d2463d8cc',
    messagingSenderId: '666491525925',
    projectId: 'fir-cloud-f6c2a',
    storageBucket: 'fir-cloud-f6c2a.appspot.com',
    iosClientId: '666491525925-5jfon156rue0crp1l8ie7e5se6a0sahh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );
}
